In [1]:
import pandas as pd

df = pd.read_csv("anemia_master_clean.csv")

df.head()

,Age in 5-year groups,Type of place of residence,Highest educational level,Wealth index combined,Births in last five years,Age of respondent at 1st birth,Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal),Anemia level,Have mosquito bed net for sleeping (from household questionnaire),Smokes cigarettes,Current marital status,Currently residing with husband/partner,When child put to breast,Had fever in last two weeks,Hemoglobin level adjusted for altitude (g/dl - 1 decimal),Anemia level.1,"Taking iron pills, sprinkles or syrup",source_file
0,40-44,Urban,Higher,Richest,1,22,NaN,NaN,Yes,No,Living with partner,Staying elsewhere,Immediately,No,NaN,NaN,Yes,children anemia.csv
1,35-39,Urban,Higher,Richest,1,28,NaN,NaN,Yes,No,Married,Living with her,Hours: 1,No,NaN,NaN,No,children anemia.csv
2,25-29,Urban,Higher,Richest,1,26,NaN,NaN,No,No,Married,Living with her,Immediately,No,NaN,NaN,No,children anemia.csv
3,20-24,Urban,Secondary,Richest,1,21,NaN,NaN,Yes,No,No longer living together/separated,NaN,Immediately,No,NaN,NaN,No,children anemia.csv
4,30-34,Urban,Secondary,Richest,1,32,NaN,NaN,Yes,No,Married,Living with her,Immediately,No,NaN,NaN,No,children anemia.csv


In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28754 entries, 0 to 28753
Data columns (total 18 columns):
 #   Column                                                                 Non-Null Count  Dtype  
---  ------                                                                 --------------  -----  
 0   Age in 5-year groups                                                   28754 non-null  object 
 1   Type of place of residence                                             28754 non-null  object 
 2   Highest educational level                                              28754 non-null  object 
 3   Wealth index combined                                                  28754 non-null  object 
 4   Births in last five years                                              28754 non-null  int64  
 5   Age of respondent at 1st birth                                         28754 non-null  int64  
 6   Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)  12472 non-null 

In [3]:
df.describe()

,Births in last five years,Age of respondent at 1st birth,Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal),Hemoglobin level adjusted for altitude (g/dl - 1 decimal)
count,28754.000000,28754.000000,12472.000000,8986.000000
mean,1.792690,19.596126,104.122835,92.954373
std,0.702882,4.337518,11.904977,12.526456
min,1.000000,12.000000,20.000000,29.000000
25%,1.000000,16.000000,98.000000,86.000000
50%,2.000000,19.000000,107.000000,96.000000
75%,2.000000,22.000000,113.000000,103.000000
max,6.000000,48.000000,119.000000,109.000000


In [4]:
df.isnull().sum()

Age in 5-year groups                                                         0
Type of place of residence                                                   0
Highest educational level                                                    0
Wealth index combined                                                        0
Births in last five years                                                    0
Age of respondent at 1st birth                                               0
Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)    16282
Anemia level                                                             16282
Have mosquito bed net for sleeping (from household questionnaire)            0
Smokes cigarettes                                                            0
Current marital status                                                       0
Currently residing with husband/partner                                   1676
When child put to breast                            

In [5]:
df[['Anemia level', 'Anemia level.1']].head()

,Anemia level,Anemia level.1
0,NaN,NaN
1,NaN,NaN
2,NaN,NaN
3,NaN,NaN
4,NaN,NaN


In [6]:
df[['Anemia level', 'Anemia level.1']].tail(20)

,Anemia level,Anemia level.1
28734,Mild,Mild
28735,Mild,Mild
28736,Mild,Moderate
28737,Mild,NaN
28738,Mild,NaN
28739,Mild,NaN
28740,Mild,Mild
28741,Moderate,NaN
28742,Moderate,Moderate
28743,Moderate,Moderate


In [7]:
df = df.drop(columns=['Anemia level.1'])

In [8]:
df = df.dropna(subset=['Anemia level'])

In [ ]:
df['Anemia level'].value_counts()

In [9]:
df.shape

(12472, 17)

In [10]:
X = df.drop('Anemia level', axis=1)
y = df['Anemia level']

In [11]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)

In [12]:
X = pd.get_dummies(X)

In [13]:
print(y[:10])

[0 0 1 1 0 0 0 0 0 0]


In [14]:
X.head()

,Births in last five years,Age of respondent at 1st birth,Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal),Hemoglobin level adjusted for altitude (g/dl - 1 decimal),Age in 5-year groups_15-19,Age in 5-year groups_20-24,Age in 5-year groups_25-29,Age in 5-year groups_30-34,Age in 5-year groups_35-39,Age in 5-year groups_40-44,...,When child put to breast_Hours: 1,When child put to breast_Immediately,Had fever in last two weeks_Don't know,Had fever in last two weeks_No,Had fever in last two weeks_Yes,"Taking iron pills, sprinkles or syrup_Don't know","Taking iron pills, sprinkles or syrup_No","Taking iron pills, sprinkles or syrup_Yes",source_file_anemia_only_strict.csv,source_file_children anemia.csv
7,1,24,116.0,109.0,False,False,True,False,False,False,...,False,False,False,True,False,False,True,False,False,True
8,2,19,118.0,96.0,False,True,False,False,False,False,...,False,True,False,True,False,False,False,True,False,True
10,2,22,95.0,96.0,False,False,True,False,False,False,...,False,True,False,True,False,False,False,True,False,True
11,2,22,95.0,106.0,False,False,True,False,False,False,...,False,False,False,True,False,False,False,True,False,True
13,1,23,109.0,96.0,False,False,True,False,False,False,...,False,True,False,True,False,False,True,False,False,True


In [15]:
X.shape

(12472, 77)

In [16]:
X.isnull().sum().sum()

np.int64(3654)

In [17]:
X = X.fillna(0)

In [18]:
X.isnull().sum().sum()

np.int64(0)

In [19]:
import numpy as np
np.unique(y)

array([0, 1, 2])

In [20]:
import pandas as pd

pd.Series(y).value_counts()

1    6528
0    5540
2     404
Name: count, dtype: int64

In [21]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [22]:
X_train.shape
X_test.shape

(2495, 77)

In [23]:
X_train.shape
X_test.shape

(2495, 77)

In [24]:
X_train.shape

(9977, 77)

In [25]:

X_test.shape

(2495, 77)

In [26]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(random_state=42)

model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [27]:
RandomForestClassifier(random_state=42)

RandomForestClassifier(random_state=42)

In [28]:
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [29]:
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [30]:
y_pred = model.predict(X_test)

In [31]:
y_pred[:10]

array([1, 0, 1, 1, 0, 1, 1, 1, 0, 1])

In [32]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.9579158316633266


In [33]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.91      0.95      1099
           1       0.93      1.00      0.96      1320
           2       1.00      0.93      0.97        76

    accuracy                           0.96      2495
   macro avg       0.98      0.95      0.96      2495
weighted avg       0.96      0.96      0.96      2495



In [34]:
print(y_test[:10])
print(y_pred[:10])

[1 0 1 1 0 1 1 1 0 1]
[1 0 1 1 0 1 1 1 0 1]


In [35]:
print(le.inverse_transform(y_pred[:10]))

['Moderate' 'Mild' 'Moderate' 'Moderate' 'Mild' 'Moderate' 'Moderate'
 'Moderate' 'Mild' 'Moderate']


In [36]:
sample = X_test.iloc[0:1]
pred = model.predict(sample)

print("Encoded:", pred)
print("Actual:", le.inverse_transform(pred))

Encoded: [1]
Actual: ['Moderate']


In [37]:
train_acc = model.score(X_train, y_train)
test_acc = model.score(X_test, y_test)

print("Train:", train_acc)
print("Test:", test_acc)

Train: 0.9994988473489025
Test: 0.9579158316633266


In [38]:
import joblib
joblib.dump(model, "anemia_model.pkl")

['anemia_model.pkl']

In [39]:
joblib.dump(le, "label_encoder.pkl")

['label_encoder.pkl']

In [40]:
joblib.dump(X.columns.tolist(), "model_columns.pkl")

['model_columns.pkl']

In [41]:
loaded_model = joblib.load("anemia_model.pkl")
loaded_le = joblib.load("label_encoder.pkl")
loaded_columns = joblib.load("model_columns.pkl")

In [42]:
sample_pred = loaded_model.predict(X_test[:5])
print("Predicted numbers:", sample_pred)
print("Predicted labels:", loaded_le.inverse_transform(sample_pred))

Predicted numbers: [1 0 1 1 0]
Predicted labels: ['Moderate' 'Mild' 'Moderate' 'Moderate' 'Mild']


In [1]:
import pandas as pd
import joblib

loaded_model = joblib.load("anemia_model.pkl")
loaded_le = joblib.load("label_encoder.pkl")
loaded_columns = joblib.load("model_columns.pkl")

sample_data = {
    "Age in 5-year groups": "20-24",
    "Type of place of residence": "Urban",
    "Highest educational level": "Secondary",
    "Wealth index combined": "Middle",
    "Births in last five years": 1,
    "Age of respondent at 1st birth": 20,
    "Have mosquito bed net for sleeping (from household questionnaire)": "Yes",
    "Smokes cigarettes": "No",
    "Current marital status": "Married",
    "Currently residing with husband/partner": "Yes"
}

input_df = pd.DataFrame([sample_data])
input_encoded = pd.get_dummies(input_df)

for col in loaded_columns:
    if col not in input_encoded.columns:
        input_encoded[col] = 0

input_encoded = input_encoded[loaded_columns]

pred = loaded_model.predict(input_encoded)
label = loaded_le.inverse_transform(pred)

print(pred[0])
print(label[0])

2
Severe
